name: deliverybridge CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  S3_BUCKET_NAME: deliverybridge

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Build with Gradle
      run: ./gradlew clean build -x test # 테스트 Skip

    # 디렉토리 생성
    - name: Make Directory
      run: mkdir -p deploy

    - name: Set YML
      run: |
        mkdir -p src/main/resources
        echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml
        
    - name: Set FIREBASE
      run: |
        mkdir -p src/main/resources/key
        echo "${{ secrets.FIREBASE_INFO_JSON }}" | base64 --decode > src/main/resources/key/realworld-64385-firebase-adminsdk-74i2n-46cbc6df19.json

    # Jar 파일 복사
    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy

    # appspec.yml 파일 복사
    - name: Copy appspec.yml
      run: cp appspec.yml ./deploy

    # script files 복사
    - name: Copy script
      run: cp ./scripts/*.sh ./deploy

    - name: Make zip file
      run: zip -r ./deliverybridge.zip ./deploy
      shell: bash

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Upload to S3
      run: aws s3 cp --region ap-northeast-2 ./deliverybridge.zip s3://deliverybridge/

    # Deploy
    - name: Deploy
      run: |
        aws deploy create-deployment \
          --application-name deliverybridge \
          --deployment-group-name deliverybridge-group \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=deliverybridge,bundleType=zip,key=deliverybridge.zip \
          --region ap-northeast-2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
